<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "keypic"
 *
 * Auto generated by Extension Builder 2014-08-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Keypic Web Service API',
	'description' => 'TYPO3 Extension to use Keypic Web Service',
	'category' => 'fe',
	'author' => 'Tomita Militaru',
	'author_email' => 'mail@tomitamilitaru.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);